[tool.poetry]
name = "insidertrader"
version = "0.1.3"  # Increment this version as needed
description = "A tool for insider trading analysis."
authors = ["Tuhin Mallick <contact@tuhinmallick.com>"]
license = "MIT"  # Replace with your project's license
readme = "README.md"
homepage = "https://github.com/tuhinmallick/InsiderTrader"
repository = "https://github.com/tuhinmallick/InsiderTrader"
keywords = ["trading", "finance", "insider trading"]
categories = ["Category :: Financial :: Investment"]

[tool.poetry.dependencies]
python = "^3.11"
# Add your project dependencies here, for example:
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0"
pytest = "^8.0.0"
# Add other development dependencies as needed

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
